### ISSUE TITLE
How to fix keystore error

### ISSUE THREAD

**Issue by tellfa** [QuixomTech/WeatherStream#1]
Hi, thanks for this awesome project.
i want clone this project but when clone , show me below error and not sync project.
please see this image for see error and help me
![68](https://user-images.githubusercontent.com/10583945/33960800-1ed22b4a-e061-11e7-924f-94b2e727e7fc.JPG)

**Comment by Fenscode** [comment]
Hey Tellfa, Thanks for using Weather Stream Github repository.

You need to create your own _keystore.properties_ inside project's folder. In our project we had defined some secret key in it, so that's why we couldn't opened publicly. 

Please go ahead to visit **OpenWeatherMap** site and create your own project and get the key, and define it in _keystore.properties_ file that I have mentioned over here.

BASE_URL = "https://api.openweathermap.org/data/2.5/"
KEY_AUTH = "x-api-key"
KEY_OPEN_WEATHER_MAP_KEY = "define_your_own_openweatherapi_key"

**Comment by tellfa** [comment]
Can you send to me simple keyStore for how to create keyStore with below data : 

BASE_URL = "https://api.openweathermap.org/data/2.5/"
KEY_AUTH = "x-api-key"
KEY_OPEN_WEATHER_MAP_KEY = "define_your_own_openweatherapi_key"

Thanks
